<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>false</EnableMsixTooling>
    <WindowsSdkPackageVersion>10.0.26100.57</WindowsSdkPackageVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>AkariToolbox</AssemblyName>
    <RootNamespace>Akari.App</RootNamespace>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <WindowsPackageType>None</WindowsPackageType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>CS1591,CA1416,MVVMTK0045</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="3.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Akari.App.Framework\AppTemplate.Framework.csproj" />
    <ProjectReference Include="..\Akari.Engine\Akari.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="tweaks.json" />
  </ItemGroup>

</Project>